name: Format Java Before Pull Request

on:
  pull_request:

jobs:
  # Format and check Linting
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: 'adopt'
      - uses: axel-op/googlejavaformat-action@v3.4.0
        with:
          args: "--skip-sorting-imports --replace"
      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.4.0
