name: Java CI with Gradle

on: [push, pull_request]

jobs:
  # Launch gradlew
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - run: chmod +x gradlew
    - run: ./gradlew build   
